# Wazuh App Copyright (C) 2019 Wazuh Inc. (License GPLv2)
version: '2'

services:
  wazuh:
    image: wazuh/wazuh:3.9.3_6.8.1
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    depends_on:
      - logstash
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
  logstash:
    image: wazuh/wazuh-logstash:3.9.3_6.8.1
    hostname: logstash
    restart: always
    links:
      - elasticsearch:elasticsearch
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    environment:
      - LS_HEAP_SIZE=2048m
      - SECURITY_ENABLED=yes
      - SECURITY_LOGSTASH_USER=service_logstash
      - SECURITY_LOGSTASH_PASS=logstash_pass
      - LOGSTASH_OUTPUT=https://elasticsearch:9200
      - ELASTICSEARCH_URL=https://elasticsearch:9200
      - SECURITY_CA_PEM=server.TEST-CA-signed.pem
  elasticsearch:
    image: wazuh/wazuh-elasticsearch:3.9.3_6.8.1
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - node.name=node-1
      - cluster.name=wazuh
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTICSEARCH_PROTOCOL=https
      - ELASTICSEARCH_IP=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - SECURITY_ENABLED=yes
      - SECURITY_ADMIN_USER=wazuh_admin
      - SECURITY_ADMIN_PASS=admin_pass
      - SECURITY_ELASTIC_PASSWORD=elastic_pass
      - SECURITY_KIBANA_USER=service_kibana
      - SECURITY_KIBANA_PASS=kibana_pass
      - SECURITY_LOGSTASH_USER=service_logstash 
      - SECURITY_LOGSTASH_PASS=logstash_pass
      - SECURITY_CA_PASSPHRASE=ca_pass
      - SECURITY_CERTIFICATE_DNS=elasticsearch
      - SECURITY_CA_PEM=server.TEST-CA-signed.pem
      - SECURITY_CA_KEY=server.TEST-CA.key
      - SECURITY_CA_TRUST=server.TEST-CA-signed.pem
      - SECURITY_MAIN_NODE=elasticsearch
      - SECURITY_OPENSSL_CONF=TEST_openssl.cnf
      - SECURITY_MONITORING_USER=service_monitoring
      - SECURITY_MONITORING_PASS=monitoring_pass
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
  kibana:
    image: wazuh/wazuh-kibana:3.9.3_6.8.1
    hostname: kibana
    restart: always
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh
    environment:
      - ELASTICSEARCH_URL=https://elasticsearch:9200
      - SECURITY_ENABLED=yes
      - SECURITY_KIBANA_USER=service_kibana
      - SECURITY_KIBANA_PASS=kibana_pass
      - SECURITY_KIBANA_SSL_KEY_PATH=/usr/share/kibana/config/ssl/private
      - SECURITY_KIBANA_SSL_CERT_PATH=/usr/share/kibana/config/ssl/certs
      - ELASTICSEARCH_KIBANA_IP=https://elasticsearch:9200
      - SECURITY_CA_PEM=server.TEST-CA-signed.pem
    ports:
      - "5601:5601"
