# Wazuh App Copyright (C) 2019 Wazuh Inc. (License GPLv2)
version: '2'

services:
  wazuh:
    image: wazuh/wazuh:3.8.2_6.5.4
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    depends_on:
      - logstash
  logstash:
    image: wazuh/wazuh-logstash:3.8.2_6.5.4
    hostname: logstash
    restart: always
    links:
      - elasticsearch:elasticsearch
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    environment:
      - LS_HEAP_SIZE=2048m
  elasticsearch:
    image: wazuh/wazuh-elasticsearch:3.8.2_6.5.4
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - node.name=node-1
      - cluster.name=wazuh
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
  kibana:
    image: wazuh/wazuh-kibana:3.8.2_6.5.4
    hostname: kibana
    restart: always
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh
  nginx:
    image: wazuh/wazuh-nginx:3.8.2_6.5.4
    hostname: nginx
    restart: always
    environment:
      - NGINX_PORT=443
      - NGINX_CREDENTIALS
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - kibana
    links:
      - kibana:kibana