# Wazuh App Copyright (C) 2019 Wazuh Inc. (License GPLv2)
filebeat:
 prospectors:
  - type: log
    paths:
     - "/var/ossec/logs/alerts/alerts.json"
    document_type: json
    json.message_key: log
    json.keys_under_root: true
    json.overwrite_keys: true
    tail_files: true

output:
 logstash:
   # The Logstash hosts
   hosts: ["logstash:5000"]
#   ssl:
#     certificate_authorities: ["/etc/filebeat/logstash.crt"]
