# Wazuh Docker Copyright (C) 2019 Wazuh Inc. (License GPLv2)

# Wazuh - Filebeat configuration file
filebeat:
 inputs:
  - type: log
    paths:
     - "/var/ossec/logs/alerts/alerts.json"

output:
 logstash:
   # The Logstash hosts
         hosts: ["logstash:5000"]
#   ssl:
#     certificate_authorities: ["/etc/filebeat/logstash.crt"]
