# Wazuh App Copyright (C) 2017, Wazuh Inc. (License GPLv2)
version: '3.7'

services:
  wazuh.agent:
    image: wazuh/wazuh-agent:5.0.0
    restart: always
    environment:
      - WAZUH_MANAGER_SERVER=<WAZUH_MANAGER_IP>
    volumes:
      - ./config/wazuh-agent-conf:/wazuh-config-mount/etc/ossec.conf